global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'vendor-api'
    static_configs:
      - targets: ['vendor:8000']

  - job_name: 'client'
    static_configs:
      - targets: ['client:8002']